# Generated by Django 6.0.5 on 2026-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_booking_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Action', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
